name: bloc_starter_template
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/auth/authentication_repository
  bloc_test: ^9.0.3
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.1.1
  flutter_screenutil: null
  google_sign_in: ^5.2.4
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  rxdart: ^0.26.0
  test: ^1.20.2
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^1.0.0
  json_serializable: ^6.0.0

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
